Update README example to v3
evergreen-ci/shrub.py pull request #35
Opened 2024-10-07 09:40 UTC by blink1073

Howdy!  We're looking to adopt `shrub.py` for `mongo-python-driver` and I figured I start by contributing back!  If you'd rather I include both v2 and v3 examples I can do that as well, but it looked like v2 is considered to be legacy at this point.

2024-10-07 23:12 UTC, zituo-jin requested changes
Thanks for updating the README. Would you mind also updating the `CHANGELOG` and bumping the version in `pyproject.toml` (like [this PR](https://github.com/evergreen-ci/shrub.py/pull/34))?

2024-10-08 00:12 UTC, blink1073 commented
Done!

2024-10-08 14:40 UTC, zituo-jin approved these changes

2024-10-08 14:44 UTC, zituo-jin commented
evergreen refresh

2024-10-08 14:46 UTC, merged